apiVersion: v1
kind: Service
metadata:
  name: marotinus
  labels:
    app: meu-marotinus
spec:
  selector:
    app: meu-marotinus
    service: marotinus
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
