apiVersion: apps/v1
kind: Deployment
metadata:
  name: marotinus
  labels:
    app: meu-marotinus
spec:
  replicas: 3
  selector:
    matchLabels:
      rs: marotinus
      app: meu-marotinus
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        rs: marotinus
        app: meu-marotinus
        service: marotinus
    spec:
      containers:
      - name: marotinus
        image: erichegt/hello-istio:0.6
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        - name: secret
          mountPath: "/secret"
          readOnly: true
        env:
        - name: AVOID_CHAOS 
          valueFrom:
            configMapKeyRef:
              name: meu-marotinus
              key: AVOID_CHAOS
        - name: DELAY_VALUE
          value: "1000"
      volumes:
      - name: config
        configMap:
          name: meu-marotinus
          items:
          - key: "test.properties"
            path: "test.properties"
      - name: secret
        secret:
          secretName: meu-marotinus
          items:
          - key: ".secret-file"
            path: ".secret-file"
