# Default values for marotinus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: erichegt/hello-istio
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 3000

resources: {}
